package graphic.cadastro;

// dao
import dao.MultaDAO;
import dao.EmprestimoDAO;

// awt
import java.awt.Color;

// swing
import javax.swing.JFrame;
import javax.swing.JOptionPane;

// modelo
import model.Multa;
import model.Emprestimo;

// suporte
import internal.JMain;
import widget.support.IPanelCRUD;

public class JCadastroMulta extends javax.swing.JPanel implements IPanelCRUD {
    
    @Override
    public boolean mostrarComoPopup() { return true; }
    
    @Override
    public String getTituloCRUD() { return "Cadastrar Multa"; }

    private int idMulta, idCliente, idEmprestimo;
    
    /**
     * Creates new form JCadastroCategoria
     */
    private JCadastroMulta() {
        initComponents();
    }
    
    public JCadastroMulta(Emprestimo emprestimo) {
        this(); // chama o costrutor padrão
        if (emprestimo != null) {
            this.idCliente = emprestimo.getIdEmprestimoCliente();
            this.idEmprestimo = emprestimo.getIdEmprestimo();
        }
    }
    
    public JCadastroMulta(Emprestimo emprestimo, Multa multa) {
        this(emprestimo); // chama outro costrutor mais simples
        this.setMulta(multa);
    }
    
    public JCadastroMulta(Multa multa) {
        
        if (multa != null) {
            System.out.println(multa);
            EmprestimoDAO dao = new EmprestimoDAO();
            Emprestimo emprestimo = dao.procurarEmprestimo(multa.getIdMultaEmprestimo());
            
            if (emprestimo != null) {
                this.idCliente = emprestimo.getIdEmprestimoCliente();
                this.idEmprestimo = emprestimo.getIdEmprestimo();
            }
            this.setMulta(multa);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescCategoria1 = new javax.swing.JTextArea();
        jLabelHeader = new javax.swing.JLabel();
        jPanelForm = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaDescMulta = new javax.swing.JTextArea();
        jLabelDescCategoria = new javax.swing.JLabel();
        jLabelNomeCategoria = new javax.swing.JLabel();
        fillerEspacamento = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(32767, 16));
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jPanelButtons = new javax.swing.JPanel();
        jButtonConcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        fillerLeft = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerCenter = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerRight = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerUpper = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        fillerLower = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        jTextAreaDescCategoria1.setColumns(20);
        jTextAreaDescCategoria1.setLineWrap(true);
        jTextAreaDescCategoria1.setRows(5);
        jTextAreaDescCategoria1.setWrapStyleWord(true);
        jTextAreaDescCategoria1.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jScrollPane1.setViewportView(jTextAreaDescCategoria1);

        setMinimumSize(new java.awt.Dimension(372, 422));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(372, 422));

        jLabelHeader.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("Cadastro Multa");

        jPanelForm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelForm.setMinimumSize(new java.awt.Dimension(344, 305));

        jTextAreaDescMulta.setColumns(20);
        jTextAreaDescMulta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextAreaDescMulta.setLineWrap(true);
        jTextAreaDescMulta.setRows(5);
        jTextAreaDescMulta.setWrapStyleWord(true);
        jTextAreaDescMulta.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jScrollPane.setViewportView(jTextAreaDescMulta);

        jLabelDescCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelDescCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescCategoria.setText("Descrição da Multa");

        jLabelNomeCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelNomeCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeCategoria.setText("Valor da Multa");

        jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        jFormattedTextFieldValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldValor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jFormattedTextFieldValor.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fillerEspacamento, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jScrollPane)
                    .addComponent(jLabelDescCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNomeCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fillerEspacamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelButtons.setLayout(new java.awt.GridBagLayout());

        jButtonConcluir.setText("Concluir");
        jButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanelButtons.add(jButtonConcluir, gridBagConstraints);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanelButtons.add(jButtonCancelar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.4;
        jPanelButtons.add(fillerLeft, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        jPanelButtons.add(fillerCenter, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.4;
        jPanelButtons.add(fillerRight, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.3;
        jPanelButtons.add(fillerUpper, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weighty = 0.3;
        jPanelButtons.add(fillerLower, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public Multa __innerGetMulta(boolean mostrarErros) {
        String valor = jFormattedTextFieldValor.getText().trim();
        String desc  = jTextAreaDescMulta.getText().trim();
        
        String msg;
        if (valor.isEmpty()) {
            msg = "o campo \"Valor da Multa\" não foi preenchido";
        } else if (desc.isEmpty()) {
            msg = "o campo \"Descrição da Multa\" não foi preenchido";
        } else {
            
            double valorDbl = Double.parseDouble(valor.replace(",", "."));
            if (valorDbl <= 0.0) {
                msg = "o valor da multa deve ser maior do que zero";
            } else {
                return new Multa(
                    idMulta, idCliente, idEmprestimo,
                        desc, valorDbl, false
                );
            }
        }
        
        if (mostrarErros) {
            JOptionPane.showMessageDialog(new JFrame(), 
                msg, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
    
    // ========== GETTER ==========
    
    public Multa getMulta() {
        return __innerGetMulta(false);
    }
    
    // ========== SETTER ==========
    
    public final void setMulta(Multa multa) {
        
        if (multa != null) {
            jFormattedTextFieldValor.setText(
                String.valueOf(multa.getValorMulta()).replace(".", ",")
            );
            jTextAreaDescMulta.setText(multa.getDescricaoMulta().trim());
            
            this.idMulta = multa.getIdMulta();
            this.idCliente = multa.getIdMultaCliente();
            this.idEmprestimo = multa.getIdMultaEmprestimo();
            
        } else {
            jFormattedTextFieldValor.setText("");
            jTextAreaDescMulta.setText("");
            
            this.idMulta = 0;
            this.idCliente = 0;
            this.idEmprestimo = 0;
        }
    }
    
    private void jButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirActionPerformed
        
        Multa multa = this.__innerGetMulta(true);
        MultaDAO dao = new MultaDAO();
        if (multa != null) {
            
            if (multa.getIdMulta() == 0) {
                if (dao.salvar(multa)) {
                    JOptionPane.showMessageDialog(new JFrame(), 
                        "multa salva com sucesso!", "Multa salva",
                            JOptionPane.INFORMATION_MESSAGE);
                    JMain.getInstancia().popJanelaCRUD();
                    return;
                }
                
                JOptionPane.showMessageDialog(new JFrame(),
                    "não foi possível salvar a multa",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                
            } else {
                if (dao.alterar(multa)) {
                    JOptionPane.showMessageDialog(new JFrame(), 
                        "multa alterada com sucesso!", "Multa alterada",
                            JOptionPane.INFORMATION_MESSAGE);
                    JMain.getInstancia().popJanelaCRUD();
                    return;
                }
                
                JOptionPane.showMessageDialog(new JFrame(),
                    "não foi possível alterar a multa",
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        lembreteCamposEmBranco();
    }//GEN-LAST:event_jButtonConcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        JMain.getInstancia().popJanelaCRUD();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

        /**
     * Coloca a cor dos componentes para uma cor vermelho claro 
     * para mostrar que o usuario não os preencheu
     */
    private void lembreteCamposEmBranco(){
        Color cor = new Color(248, 220, 219);

        if (jFormattedTextFieldValor.getText().isEmpty()) {
            jFormattedTextFieldValor.setBackground(cor);
        } else {
            jFormattedTextFieldValor.setBackground(Color.WHITE);
        }

        if (jTextAreaDescMulta.getText().isEmpty()) {
            jTextAreaDescMulta.setBackground(cor);
        } else {
            jTextAreaDescMulta.setBackground(Color.WHITE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler fillerCenter;
    private javax.swing.Box.Filler fillerEspacamento;
    private javax.swing.Box.Filler fillerLeft;
    private javax.swing.Box.Filler fillerLower;
    private javax.swing.Box.Filler fillerRight;
    private javax.swing.Box.Filler fillerUpper;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConcluir;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JLabel jLabelDescCategoria;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelNomeCategoria;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescCategoria1;
    private javax.swing.JTextArea jTextAreaDescMulta;
    // End of variables declaration//GEN-END:variables
}
