package graphic.cadastro;

// dao
import dao.CategoriaDAO;

// awt
import java.awt.Color;

// swing
import javax.swing.JFrame;
import javax.swing.JOptionPane;

// modelo
import model.Categoria;

// suporte
import internal.JMain;
import widget.support.IPanelCRUD;

public class JCadastroCategoria extends javax.swing.JPanel implements IPanelCRUD {
    
    @Override
    public boolean mostrarComoPopup() { return true; }
    
    @Override
    public String getTituloCRUD() { return "Cadastrar Categoria"; }

    private int idCategoria;
    
    /**
     * Creates new form JCadastroCategoria
     */
    public JCadastroCategoria() {
        initComponents();
    }
    
    public JCadastroCategoria(Categoria categoria) {
        this(); // chama o costrutor padrão
        setCategoria(categoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescCategoria1 = new javax.swing.JTextArea();
        jLabelHeader = new javax.swing.JLabel();
        jPanelForm = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaDescCategoria = new javax.swing.JTextArea();
        jLabelDescCategoria = new javax.swing.JLabel();
        jLabelNomeCategoria = new javax.swing.JLabel();
        jTextFieldNomeCategoria = new javax.swing.JTextField();
        fillerEspacamento = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(32767, 16));
        jPanelButtons = new javax.swing.JPanel();
        jButtonConcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        fillerLeft = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerCenter = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerRight = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerUpper = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        fillerLower = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        jTextAreaDescCategoria1.setColumns(20);
        jTextAreaDescCategoria1.setLineWrap(true);
        jTextAreaDescCategoria1.setRows(5);
        jTextAreaDescCategoria1.setWrapStyleWord(true);
        jTextAreaDescCategoria1.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jScrollPane1.setViewportView(jTextAreaDescCategoria1);

        setMinimumSize(new java.awt.Dimension(372, 422));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(372, 422));

        jLabelHeader.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader.setText("Cadastro Categoria");

        jPanelForm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelForm.setMinimumSize(new java.awt.Dimension(344, 305));

        jTextAreaDescCategoria.setColumns(20);
        jTextAreaDescCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextAreaDescCategoria.setLineWrap(true);
        jTextAreaDescCategoria.setRows(5);
        jTextAreaDescCategoria.setWrapStyleWord(true);
        jTextAreaDescCategoria.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jScrollPane.setViewportView(jTextAreaDescCategoria);

        jLabelDescCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelDescCategoria.setText("Descrição da Categoria");

        jLabelNomeCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelNomeCategoria.setText("Nome da Categoria");

        jTextFieldNomeCategoria.setColumns(30);
        jTextFieldNomeCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDescCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fillerEspacamento, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jScrollPane)
                    .addComponent(jTextFieldNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fillerEspacamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelButtons.setLayout(new java.awt.GridBagLayout());

        jButtonConcluir.setText("Concluir");
        jButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanelButtons.add(jButtonConcluir, gridBagConstraints);

        jButtonCancelar.setText("Cancelar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanelButtons.add(jButtonCancelar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.4;
        jPanelButtons.add(fillerLeft, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        jPanelButtons.add(fillerCenter, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.4;
        jPanelButtons.add(fillerRight, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.3;
        jPanelButtons.add(fillerUpper, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weighty = 0.3;
        jPanelButtons.add(fillerLower, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public Categoria __innerGetCategoria(boolean mostrarErros) {
        String nome = jTextFieldNomeCategoria.getText().trim();
        String desc = jTextAreaDescCategoria.getText().trim();
        
        String msg;
        if (nome.isEmpty()) {
            msg = "o campo \"Nome da Categoria\" não foi preenchido";
        } else if (desc.isEmpty()) {
            msg = "o campo \"Descrição da Categoria\" não foi preenchido";
        } else {
            return new Categoria(idCategoria, nome, desc);
        }
        
        if (mostrarErros) {
            JOptionPane.showMessageDialog(new JFrame(), 
                msg, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
    
    // ========== GETTER ==========
    
    public Categoria getCategoria() {
        return __innerGetCategoria(false);
    }
    
    // ========== SETTER ==========
    
    public final void setCategoria(Categoria categoria) {
        
        if (categoria != null) {
            jTextFieldNomeCategoria.setText(categoria.getNomeCategoria().trim());
            jTextAreaDescCategoria.setText(categoria.getDescricaoCategoria().trim());
        } else {
            jTextFieldNomeCategoria.setText("");
            jTextAreaDescCategoria.setText("");
        }
        
        this.idCategoria = categoria.getIdCategoria();
    }
    
    private void jButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirActionPerformed
        
        Categoria categoria = this.__innerGetCategoria(true);
        CategoriaDAO dao = new CategoriaDAO();
        if (categoria != null) {
            
            if (categoria.getIdCategoria() == 0) {
                if (dao.salvar(categoria)) {
                    JOptionPane.showMessageDialog(new JFrame(), 
                        "Categoria \"" + categoria.getNomeCategoria() 
                            + "\" salva com sucesso!", "Categoria salva!",
                            JOptionPane.INFORMATION_MESSAGE);
                    JMain.getInstancia().popJanelaCRUD();
                    return;
                }
                
                JOptionPane.showMessageDialog(new JFrame(),
                    "Não foi possível salvar a categoria \"" + 
                        categoria.getNomeCategoria() + "\"!",
                        "Algo deu errado!", JOptionPane.ERROR_MESSAGE);
                
            } else {
                if (dao.alterar(categoria)) {
                    JOptionPane.showMessageDialog(new JFrame(), 
                        "Categoria \"" + categoria.getNomeCategoria() 
                            + "\" alterada com sucesso!", "Categoria alterada!",
                            JOptionPane.INFORMATION_MESSAGE);
                    JMain.getInstancia().popJanelaCRUD();
                    return;
                }
                
                JOptionPane.showMessageDialog(new JFrame(),
                    "Não foi possível alterar a categoria \"" + 
                        categoria.getNomeCategoria() + "\"!",
                        "Algo deu errado!", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        lembreteCamposEmBranco();
    }//GEN-LAST:event_jButtonConcluirActionPerformed

        /**
     * Coloca a cor dos componentes para uma cor vermelho claro 
     * para mostrar que o usuario não os preencheu
     */
    private void lembreteCamposEmBranco(){
        Color cor = new Color(248, 220, 219);

        if (jTextFieldNomeCategoria.getText().isEmpty()) {
            jTextFieldNomeCategoria.setBackground(cor);
        } else {
            jTextFieldNomeCategoria.setBackground(Color.WHITE);
        }

        if (jTextAreaDescCategoria.getText().isEmpty()) {
            jTextAreaDescCategoria.setBackground(cor);
        } else {
            jTextAreaDescCategoria.setBackground(Color.WHITE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler fillerCenter;
    private javax.swing.Box.Filler fillerEspacamento;
    private javax.swing.Box.Filler fillerLeft;
    private javax.swing.Box.Filler fillerLower;
    private javax.swing.Box.Filler fillerRight;
    private javax.swing.Box.Filler fillerUpper;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConcluir;
    private javax.swing.JLabel jLabelDescCategoria;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelNomeCategoria;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescCategoria;
    private javax.swing.JTextArea jTextAreaDescCategoria1;
    private javax.swing.JTextField jTextFieldNomeCategoria;
    // End of variables declaration//GEN-END:variables
}
