package graphic.cadastro;

// Main
import internal.Main;

// java.util
import java.util.Comparator;
import java.util.List;

// awt
import java.awt.Color;

// dao
import dao.CategoriaDAO;
import dao.LivroDAO;

// model
import model.Categoria;
import model.Livro;

// swing
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class JCadastroLivro extends javax.swing.JPanel {

    /**
     * Creates new form JCadastroLivro
     */
    public JCadastroLivro() {
        initComponents();
        listarCategorias();
    }
    
    private void listarCategorias(){
        CategoriaDAO catDao = new CategoriaDAO();
        List<Categoria> categorias = catDao.listarCategorias();
        categorias.sort(new Comparator<Categoria>() {
            @Override
            public int compare(Categoria t1, Categoria t2) {
                return t1.getNomeCategoria().compareTo(t2.getNomeCategoria());
            }
        });

        for (int i = 0; i < categorias.size(); i++) {
            jComboBoxCategoria.addItem(categorias.get(i).getNomeCategoria());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastro = new javax.swing.JLabel();
        jPanelFormParteA = new javax.swing.JPanel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabelNomeLivro = new javax.swing.JLabel();
        jTextFieldNomeLivro = new javax.swing.JTextField();
        jLabelEdicao = new javax.swing.JLabel();
        jFormattedTextFieldEdicao = new javax.swing.JFormattedTextField();
        jLabelDataLancamento = new javax.swing.JLabel();
        jFormattedTextFieldDataLancamento = new javax.swing.JFormattedTextField();
        jLabelNomeEditora = new javax.swing.JLabel();
        jTextFieldNomeEditora = new javax.swing.JTextField();
        jLabelISBN = new javax.swing.JLabel();
        jLabelNomeAutor = new javax.swing.JLabel();
        jTextFieldNomeAutor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldPaginas = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPreco = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPaneSinopse = new javax.swing.JScrollPane();
        jTextAreaSinopse = new javax.swing.JTextArea();
        jPanelButtons = new javax.swing.JPanel();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabelCadastro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastro.setText("Cadastro Livro");

        jPanelFormParteA.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldISBNActionPerformed(evt);
            }
        });
        jTextFieldISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldISBNKeyTyped(evt);
            }
        });

        jLabelNomeLivro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelNomeLivro.setText("Nome do Livro");

        jTextFieldNomeLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeLivroActionPerformed(evt);
            }
        });

        jLabelEdicao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelEdicao.setText("Edição");

        jFormattedTextFieldEdicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldEdicao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldEdicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldEdicaoKeyTyped(evt);
            }
        });

        jLabelDataLancamento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelDataLancamento.setText("Lançamento");

        try {
            jFormattedTextFieldDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataLancamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldDataLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataLancamentoActionPerformed(evt);
            }
        });

        jLabelNomeEditora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelNomeEditora.setText("Editora");

        jLabelISBN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelISBN.setText("ISBN");

        jLabelNomeAutor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelNomeAutor.setText("Autor");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Categoria");

        jComboBoxCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxCategoria.setMinimumSize(new java.awt.Dimension(162, 22));
        jComboBoxCategoria.setPreferredSize(new java.awt.Dimension(162, 22));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Páginas");

        jFormattedTextFieldPaginas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####0"))));
        jFormattedTextFieldPaginas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldPaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPaginasKeyTyped(evt);
            }
        });

        jFormattedTextFieldPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldPreco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPrecoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Preço");

        javax.swing.GroupLayout jPanelFormParteALayout = new javax.swing.GroupLayout(jPanelFormParteA);
        jPanelFormParteA.setLayout(jPanelFormParteALayout);
        jPanelFormParteALayout.setHorizontalGroup(
            jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormParteALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldNomeLivro)
                        .addComponent(jLabelNomeLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                    .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelNomeAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormParteALayout.createSequentialGroup()
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jTextFieldISBN))
                        .addGap(10, 10, 10)
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFormParteALayout.createSequentialGroup()
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelNomeEditora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextFieldEdicao)
                            .addComponent(jLabelEdicao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDataLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFormParteALayout.setVerticalGroup(
            jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormParteALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFormParteALayout.createSequentialGroup()
                        .addComponent(jLabelNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNomeAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormParteALayout.createSequentialGroup()
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelISBN)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormParteALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelFormParteALayout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jTextFieldNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormParteALayout.createSequentialGroup()
                                .addComponent(jLabelEdicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormParteALayout.createSequentialGroup()
                                .addComponent(jLabelDataLancamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Sinopse");

        jTextAreaSinopse.setColumns(20);
        jTextAreaSinopse.setLineWrap(true);
        jTextAreaSinopse.setRows(5);
        jTextAreaSinopse.setWrapStyleWord(true);
        jScrollPaneSinopse.setViewportView(jTextAreaSinopse);

        jButtonConfirmar.setText("Concluir");
        jButtonConfirmar.setMaximumSize(new java.awt.Dimension(125, 25));
        jButtonConfirmar.setMinimumSize(new java.awt.Dimension(125, 25));
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(125, 25));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(125, 25));

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPaneSinopse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 144, Short.MAX_VALUE)
                        .addComponent(jPanelFormParteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelFormParteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeLivroActionPerformed

    private void jTextFieldISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldISBNActionPerformed

    private void jFormattedTextFieldDataLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataLancamentoActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        LivroDAO livroDao = new LivroDAO();
        Livro livro = new Livro();

        String nome = jTextFieldNomeLivro.getText();
        String isbn = jTextFieldISBN.getText();
        String autor = jTextFieldNomeAutor.getText();
        String editora = jTextFieldNomeEditora.getText();
        String edicao = jFormattedTextFieldEdicao.getText();
        String dataLancamento = jFormattedTextFieldDataLancamento.getText();
        String categoria = (String) jComboBoxCategoria.getSelectedItem();
        String paginas = jFormattedTextFieldPaginas.getText();
        String preco = jFormattedTextFieldPreco.getText().replace(",", ".");
        String sinopse = jTextAreaSinopse.getText();

        if (!(nome.isEmpty() ||
            !Main.validaISBN(isbn) ||
            autor.isEmpty() ||
            editora.isEmpty() ||
            edicao.isEmpty() ||
            dataLancamento.equals("  /  /    ") ||
            categoria.isEmpty() ||
            paginas.isEmpty() ||
            preco.isEmpty() ||
            sinopse.isEmpty())) {

            livro.setNomeLivro(nome);
            livro.setISBNLivro(isbn.replace("-", ""));
            livro.setAutorLivro(autor);
            livro.setEditoraLivro(editora);
            livro.setEdicaoLivro(Integer.parseInt(edicao));
            livro.setDataLancamentoLivro(Main.formataData(dataLancamento));
            livro.setNomeLivroCategoria(categoria);
            livro.setPaginasLivro(Integer.parseInt(paginas));
            livro.setPrecoLivro(Double.parseDouble(preco));
            livro.setSinopseLivro(sinopse);

            if (livroDao.salvar(livro)) {
                JOptionPane.showMessageDialog(new JFrame(),
                    "Livro " + nome + " salvo com sucesso!", "Livro salvo!", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(new JFrame(),
                    "Não foi possível salvar o livro", "Algo deu errado!", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }

        lembreteCamposEmBranco();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

        /**
     * Coloca a cor dos componentes para uma cor vermelho claro 
     * para mostrar que o usuario não os preencheu
     */
    private void lembreteCamposEmBranco(){
        Color cor = new Color(248, 220, 219);

        if (jTextFieldNomeLivro.getText().isEmpty()) {
            jTextFieldNomeLivro.setBackground(cor);
        } else {
            jTextFieldNomeLivro.setBackground(Color.WHITE);
        }

        if (!Main.validaISBN(jTextFieldISBN.getText())) {
            jTextFieldISBN.setBackground(cor);
        } else {
            jTextFieldISBN.setBackground(Color.WHITE);
        }

        if (jTextFieldNomeAutor.getText().isEmpty()) {
            jTextFieldNomeAutor.setBackground(cor);
        } else {
            jTextFieldNomeAutor.setBackground(Color.WHITE);
        }

        if(jTextFieldNomeEditora.getText().isEmpty()) {
            jTextFieldNomeEditora.setBackground(cor);
        } else {
            jTextFieldNomeEditora.setBackground(Color.WHITE);
        }

        if (jFormattedTextFieldEdicao.getText().isEmpty()) {
            jFormattedTextFieldEdicao.setBackground(cor);
        } else {
            jFormattedTextFieldEdicao.setBackground(Color.WHITE);
        }

        if (jFormattedTextFieldDataLancamento.getText().equals("  /  /    ")) {
            jFormattedTextFieldDataLancamento.setBackground(cor);
        } else {
            jFormattedTextFieldDataLancamento.setBackground(Color.WHITE);
        }

        if (jComboBoxCategoria.getSelectedItem() == null) {
            jComboBoxCategoria.setBackground(cor);
        } else {
            jComboBoxCategoria.setBackground(Color.WHITE);
        }

        if (jFormattedTextFieldPaginas.getText().isEmpty()) {
            jFormattedTextFieldPaginas.setBackground(cor);
        } else {
            jFormattedTextFieldPaginas.setBackground(Color.WHITE);
        }

        if (jFormattedTextFieldPreco.getText().isEmpty()) {
            jFormattedTextFieldPreco.setBackground(cor);
        } else {
            jFormattedTextFieldPreco.setBackground(Color.WHITE);
        }

        if (jTextAreaSinopse.getText().isEmpty()) {
            jTextAreaSinopse.setBackground(cor);
        } else {
            jTextAreaSinopse.setBackground(Color.WHITE);
        }
    }
    
    private void jFormattedTextFieldPaginasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPaginasKeyTyped
        String charsPermitidos = "0123456789";
            if(!charsPermitidos.contains(evt.getKeyChar()+""))
                evt.consume();
    }//GEN-LAST:event_jFormattedTextFieldPaginasKeyTyped

    private void jFormattedTextFieldEdicaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEdicaoKeyTyped
        String charsPermitidos = "0123456789";
            if(!charsPermitidos.contains(evt.getKeyChar()+""))
                evt.consume();
    }//GEN-LAST:event_jFormattedTextFieldEdicaoKeyTyped

    private void jFormattedTextFieldPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecoKeyTyped
        String charsPermitidos = "0123456789,";
            if(!charsPermitidos.contains(evt.getKeyChar()+"") ||
                    (evt.getKeyChar() == ',' && quantidadeCaracteres(evt.getKeyChar(), jFormattedTextFieldPreco.getText()) >= 1))
                evt.consume();
    }//GEN-LAST:event_jFormattedTextFieldPrecoKeyTyped

    private void jTextFieldISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldISBNKeyTyped
        String charsPermitidos = "0123456789-";
        if(!charsPermitidos.contains(evt.getKeyChar()+"") ||
                (evt.getKeyChar() == '-' && 
                Main.ultimoCharIgual(evt.getKeyChar(), jTextFieldISBN.getText())) ||
                jTextFieldISBN.getText().length() >= 17)//13 números + 4 traçõs no máximo = 17 caracteres
            evt.consume();
    }//GEN-LAST:event_jTextFieldISBNKeyTyped

    /**
     * Retorna a quantidade de vezes em que o caractere c aparece na String s
     * 
     * @param c o char para verificar
     * @param s a String para ver quantas vezes ela possui o char c
     * @return  a quantidade de vezes que c aparece em s
     */
    private int quantidadeCaracteres(char c, String s) {
        int quantidade = 0;
        
        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) == c) quantidade++;
        }
        
        return quantidade;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataLancamento;
    private javax.swing.JFormattedTextField jFormattedTextFieldEdicao;
    private javax.swing.JFormattedTextField jFormattedTextFieldPaginas;
    private javax.swing.JFormattedTextField jFormattedTextFieldPreco;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelDataLancamento;
    private javax.swing.JLabel jLabelEdicao;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelNomeAutor;
    private javax.swing.JLabel jLabelNomeEditora;
    private javax.swing.JLabel jLabelNomeLivro;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelFormParteA;
    private javax.swing.JScrollPane jScrollPaneSinopse;
    private javax.swing.JTextArea jTextAreaSinopse;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldNomeAutor;
    private javax.swing.JTextField jTextFieldNomeEditora;
    private javax.swing.JTextField jTextFieldNomeLivro;
    // End of variables declaration//GEN-END:variables
}
