/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic.util;

// swing
import javax.swing.JPanel;

// awt
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.Component;
import java.awt.Dimension;

// java util
import java.util.List;

// modelos
import model.Livro;

// graphic.util.livro
import graphic.util.livro.IComponenteLivro;

// java lang.reflect
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;

/**
 *
 * @author giovani
 */
public class JListaLivros extends javax.swing.JPanel {
    
    private ComponentAdapter resizeListener;
    
    /**
     * Creates new form JListaLivros
     */
    public JListaLivros() {
        initComponents();
        init();
    }
    
    private void init() {
        var dim = jPanelLivros.getPreferredSize();
        dim.height = 0;
        jPanelLivros.setPreferredSize(dim);
        
        // observador de redimensinamento
        resizeListener = new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                conteudoRedimensionado();
            }
        };
    }
    
    // inspirado por: https://stackoverflow.com/questions/75175/create-instance-of-generic-type-in-java
    // permite a adição de qualquer JPanel que implemente a interface IComponenteLivro
    public <T extends JPanel & IComponenteLivro>
    void inserirLivros(List<Livro> livros, Class<T> cls) {
        var dim = jPanelLivros.getPreferredSize();
        Constructor<T> constructor;
        try {
            constructor = cls.getDeclaredConstructor(Livro.class);
        } catch(NoSuchMethodException e) {
            throw new RuntimeException(e);
        }
        for (Livro p : livros) {
            try {
                T livro = constructor.newInstance(p);
                jPanelLivros.add(livro);
                dim.height += livro.getPreferredSize().height;
                livro.addComponentListener(resizeListener);
            } catch(
                InstantiationException | 
                IllegalAccessException | 
                InvocationTargetException e) { throw new RuntimeException(e); }
        }
        jPanelLivros.setPreferredSize(dim);
        jPanelLivros.revalidate();
    }
    
    // força o JPanel dentro do JScrollPane a ter o tamanho necessário
    // para comportar todos os componentes, mesmo que haja redimensionamento
    public void conteudoRedimensionado() {
        var dim = new Dimension(0, 0);
        for (Component comp : jPanelLivros.getComponents()) {
            var tmp = comp.getPreferredSize();
            dim.height += tmp.height;
            dim.width = (tmp.width > dim.width ? tmp.width:dim.width);
        }
        int delta = dim.height - jPanelLivros.getPreferredSize().height;
        if (Math.abs(delta) > 0) {
            jPanelLivros.setPreferredSize(dim);
            jPanelLivros.revalidate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneLivros = new javax.swing.JScrollPane();
        jPanelLivros = new javax.swing.JPanel();
        jBarraPesquisa1 = new graphic.util.JBarraPesquisa();

        setPreferredSize(new java.awt.Dimension(600, 600));

        jScrollPaneLivros.setPreferredSize(new java.awt.Dimension(576, 533));

        jPanelLivros.setPreferredSize(new java.awt.Dimension(573, 530));
        jPanelLivros.setLayout(new javax.swing.BoxLayout(jPanelLivros, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneLivros.setViewportView(jPanelLivros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBarraPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBarraPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private graphic.util.JBarraPesquisa jBarraPesquisa1;
    private javax.swing.JPanel jPanelLivros;
    private javax.swing.JScrollPane jScrollPaneLivros;
    // End of variables declaration//GEN-END:variables
}
