package widget.listas;

// awt
import java.awt.Dimension;

// java util
import java.util.List;

// modelos
import model.Cliente;
import widget.dados.JDadosCliente;

public class JListaClientes extends javax.swing.JPanel {
    
    /**
     * Creates new form JListaLivros
     */
    public JListaClientes() {
        initComponents();
        init();
    }
    
    private void init() {
        Dimension dim = jPanelClientes.getPreferredSize();
        dim.height = 0;
        jPanelClientes.setPreferredSize(dim);
    }
    
    public void inserirClientes(List<Cliente> clientes) {
        Dimension dim = jPanelClientes.getPreferredSize();
        
        for (Cliente p : clientes) {
            JDadosCliente cliente = new JDadosCliente(p);
            jPanelClientes.add(cliente);
            dim.height += cliente.getPreferredSize().height;
        }
        jPanelClientes.setPreferredSize(dim);
        jPanelClientes.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneClientes = new javax.swing.JScrollPane();
        jPanelClientes = new javax.swing.JPanel();
        jBarraPesquisaSimples1 = new widget.JBarraPesquisaSimples();

        setPreferredSize(new java.awt.Dimension(566, 600));

        jScrollPaneClientes.setMinimumSize(new java.awt.Dimension(542, 22));
        jScrollPaneClientes.setPreferredSize(new java.awt.Dimension(542, 533));

        jPanelClientes.setPreferredSize(new java.awt.Dimension(524, 530));
        jPanelClientes.setLayout(new javax.swing.BoxLayout(jPanelClientes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneClientes.setViewportView(jPanelClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBarraPesquisaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBarraPesquisaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.JBarraPesquisaSimples jBarraPesquisaSimples1;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JScrollPane jScrollPaneClientes;
    // End of variables declaration//GEN-END:variables
}
