package widget.listas;

// java util
import java.util.List;

// modelos
import model.Usuario;
import widget.dados.JDadosUsuario;


public class JListaUsuarios extends javax.swing.JPanel {
    
    /**
     * Creates new form JListaLivros
     */
    public JListaUsuarios() {
        initComponents();
        init();
    }
    
    private void init() {
        var dim = jPanelUsuarios.getPreferredSize();
        dim.height = 0;
        jPanelUsuarios.setPreferredSize(dim);
    }
    
    public void inserirUsuarios(List<Usuario> usuarios) {
        var dim = jPanelUsuarios.getPreferredSize();
        
        for (Usuario p : usuarios) {
            JDadosUsuario usuario = new JDadosUsuario(p);
            jPanelUsuarios.add(usuario);
            dim.height += usuario.getPreferredSize().height;
        }
        jPanelUsuarios.setPreferredSize(dim);
        jPanelUsuarios.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneUsuarios = new javax.swing.JScrollPane();
        jPanelUsuarios = new javax.swing.JPanel();
        jBarraPesquisaSimples1 = new widget.JBarraPesquisaSimples();

        setPreferredSize(new java.awt.Dimension(566, 600));

        jScrollPaneUsuarios.setMinimumSize(new java.awt.Dimension(542, 22));
        jScrollPaneUsuarios.setPreferredSize(new java.awt.Dimension(542, 533));

        jPanelUsuarios.setPreferredSize(new java.awt.Dimension(524, 530));
        jPanelUsuarios.setLayout(new javax.swing.BoxLayout(jPanelUsuarios, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneUsuarios.setViewportView(jPanelUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBarraPesquisaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBarraPesquisaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.JBarraPesquisaSimples jBarraPesquisaSimples1;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JScrollPane jScrollPaneUsuarios;
    // End of variables declaration//GEN-END:variables
}
