package widget.listas;

// awt
import java.awt.Dimension;

// java util
import java.util.List;

// dao
import dao.UsuarioDAO;

// modelos
import model.Usuario;

// widget
import widget.dados.JDadosUsuario;

// suporte
import widget.support.IPanelCRUD;

public class JListaUsuarios extends javax.swing.JPanel implements IListaDados, IPanelCRUD {
    
    @Override
    public boolean mostrarComoPopup() { return false; }
    
    @Override
    public String getTituloCRUD() { return "Lista de Usuários"; }
    
    /**
     * Creates new form JListaLivros
     */
    public JListaUsuarios() {
        initComponents();
        init();
    }
    
    private void init() {
        Dimension dim = jPanelUsuarios.getPreferredSize();
        dim.height = 0;
        jPanelUsuarios.setPreferredSize(dim);
    }
    
    public void inserirUsuarios(List<Usuario> usuarios) {
        Dimension dim = jPanelUsuarios.getPreferredSize();
        
        for (Usuario p : usuarios) {
            JDadosUsuario usuario = new JDadosUsuario(p);
            jPanelUsuarios.add(usuario);
            dim.height += usuario.getPreferredSize().height;
        }
        jPanelUsuarios.setPreferredSize(dim);
        jPanelUsuarios.revalidate();
    }
    
    // ==================== implements IListaDados ====================
    
    /**
     * carrega os usuários do banco na lista se a lista estiver vazia e
     * retorna se o conteúdo da lista foi alterado
     * 
     * @return true se o conteúdo da lista for alterado, do contrario false
     */
    @Override
    public boolean carregar() {
        // previne duplicação de dados
        if (jPanelUsuarios.getComponentCount() > 0) return false;
        
        // carrega os dados
        UsuarioDAO dao = new UsuarioDAO();
        inserirUsuarios(dao.listarUsuarios());
        return true;
    }
    
    /**
     * carrega mais usuários do banco de dados, inserindo-os na lista
     * 
     * @param contagem número de usuários para carregar
     */
    @Override
    public void carregar(int contagem) {
        UsuarioDAO dao = new UsuarioDAO();
        inserirUsuarios(dao.listarUsuarios(this.comprimento(), contagem));
    }
    
    /**
     * remove todos os usuários da lista, tornando-a vazia
     */
    @Override
    public void esvaziar() {
        jPanelUsuarios.removeAll();
        jPanelUsuarios.setPreferredSize(
            new Dimension(jPanelUsuarios.getPreferredSize().width, 0)
        );
    }
    
    /**
     * retorna o comprimento da lista em número de usuários
     * 
     * @return o comprimento da lista
     */
    @Override
    public int comprimento() {
        return jPanelUsuarios.getComponentCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneUsuarios = new javax.swing.JScrollPane();
        jPanelUsuarios = new javax.swing.JPanel();
        jBarraPesquisaSimples1 = new widget.JBarraPesquisaSimples();

        setPreferredSize(new java.awt.Dimension(566, 600));

        jScrollPaneUsuarios.setMinimumSize(new java.awt.Dimension(542, 22));
        jScrollPaneUsuarios.setPreferredSize(new java.awt.Dimension(542, 533));

        jPanelUsuarios.setPreferredSize(new java.awt.Dimension(524, 530));
        jPanelUsuarios.setLayout(new javax.swing.BoxLayout(jPanelUsuarios, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneUsuarios.setViewportView(jPanelUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBarraPesquisaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPaneUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBarraPesquisaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.JBarraPesquisaSimples jBarraPesquisaSimples1;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JScrollPane jScrollPaneUsuarios;
    // End of variables declaration//GEN-END:variables
}
