package widget.listas;

// awt
import java.awt.Dimension;

// java util
import java.util.List;

// dao
import dao.MultaDAO;

// modelos
import model.Multa;

// widget
import widget.dados.JDadosMulta;

public class JListaMultas extends javax.swing.JPanel implements IListaDados {
    
    /**
     * Creates new form JListaLivros
     */
    public JListaMultas() {
        initComponents();
        init();
    }
    
    private void init() {
        Dimension dim = jPanelLivros.getPreferredSize();
        dim.height = 0;
        jPanelLivros.setPreferredSize(dim);
    }
    
    public void inserirMultas(List<Multa> multas) {
        Dimension dim = jPanelLivros.getPreferredSize();
        
        for (Multa p : multas) {
            JDadosMulta multa = new JDadosMulta(p);
            jPanelLivros.add(multa);
            dim.height += multa.getPreferredSize().height;
        }
        jPanelLivros.setPreferredSize(dim);
        jPanelLivros.revalidate();
    }
    
    // ==================== implements IListaDados ====================
    
    /**
     * carrega as multas do banco na lista se ela estiver vazia e
     * retorna se o conteúdo foi alterado
     * 
     * @return true se o conteúdo da lista for alterado, do contrario false
     */
    @Override
    public boolean carregar() {
        // previne duplicação de dados
        if (jPanelLivros.getComponentCount() > 0) return false;
        
        // carrega os dados
        MultaDAO dao = new MultaDAO();
        inserirMultas(dao.listarMultas());
        return true;
    }
    
    /**
     * carrega mais multas do banco de dados, inserindo-os na lista
     * 
     * @param contagem número de multas para carregar
     */
    @Override
    public void carregar(int contagem) {
        MultaDAO dao = new MultaDAO();
        inserirMultas(dao.listarMultas(this.comprimento(), contagem));
    }
    
    /**
     * remove todos as multas da lista, tornando-a vazia
     */
    @Override
    public void esvaziar() {
        jPanelLivros.removeAll();
        jPanelLivros.setPreferredSize(
            new Dimension(jPanelLivros.getPreferredSize().width, 0)
        );
    }
    
    /**
     * retorna o comprimento da lista em número de multas
     * 
     * @return o comprimento da lista
     */
    @Override
    public int comprimento() {
        return jPanelLivros.getComponentCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneLivros = new javax.swing.JScrollPane();
        jPanelLivros = new javax.swing.JPanel();
        jBarraPesquisaSimples1 = new widget.JBarraPesquisaSimples();

        setPreferredSize(new java.awt.Dimension(566, 600));

        jScrollPaneLivros.setMinimumSize(new java.awt.Dimension(537, 22));
        jScrollPaneLivros.setPreferredSize(new java.awt.Dimension(542, 533));

        jPanelLivros.setPreferredSize(new java.awt.Dimension(520, 520));
        jPanelLivros.setLayout(new javax.swing.BoxLayout(jPanelLivros, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneLivros.setViewportView(jPanelLivros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBarraPesquisaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPaneLivros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBarraPesquisaSimples1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneLivros, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.JBarraPesquisaSimples jBarraPesquisaSimples1;
    private javax.swing.JPanel jPanelLivros;
    private javax.swing.JScrollPane jScrollPaneLivros;
    // End of variables declaration//GEN-END:variables
}
