/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic.util.livro;

import java.awt.event.ActionListener;
import model.Livro;

/**
 *
 * @author giovani
 */
public class JHeaderLivro extends javax.swing.JPanel {

    private JDadosLivro mestre;
    
    /**
     * Creates new form DadosLivro
     */
    public JHeaderLivro() {
        initComponents();
    }
    
    public void atualizarConteudo() {
        if (mestre == null) return;
        
        Livro livro = mestre.getLivro();
        if (livro == null) return;
        
        jLabelTitulo.setText(livro.getNomeLivro());
        jLabelISBN.setText(livro.getISBNLivro());
    }
    
    // ========== setters ==========
    
    public void setMestre(JDadosLivro mestre) {
        this.mestre = mestre;
    }
    
    // ========== getters ==========
    
    public JDadosLivro getMestre() {
        return this.mestre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelISBN = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonDropdown = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 0));

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo.setText("Titulo do Livro");

        jLabelISBN.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabelISBN.setText("ISBN: 123-456789ABCD");

        jButtonAdicionar.setText("+");
        jPanelButtons.add(jButtonAdicionar);

        jButtonDropdown.setText("^");
        jPanelButtons.add(jButtonDropdown);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void addActionListenerDropdown(ActionListener l) {
        jButtonDropdown.addActionListener(l);
    }
    public void removeActionListenerDropdown(ActionListener l) {
        jButtonDropdown.removeActionListener(l);
    }
    public ActionListener[] getActionListenersDropdown() {
        return jButtonDropdown.getActionListeners();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonDropdown;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelButtons;
    // End of variables declaration//GEN-END:variables
}
