package widget.dados;

// awt
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Dimension;

// modelo
import model.Livro;

// suporte
import widget.support.IDropdown;
import widget.support.IComponenteLivro;

// JMain
import internal.JMain;

public class JDadosLivro extends javax.swing.JPanel implements IDropdown, IComponenteLivro {

    private Livro livro;
    private boolean dropdownEstendido;
    private ActionListener actionListenerDropdown;
    
    /**
     * Creates new form JLivro
     */
    public JDadosLivro() {
        initComponents();
        init();
    }
    
    public JDadosLivro(Livro livro) {
        this();
        this.livro = livro;
        this.atualizarConteudo();
    }
    
    // pós inicialização dos componentes desse componente
    @SuppressWarnings("Convert2Lambda")
    private void init() {
        // configura se o dropdown está estendido
        if (dropdownEstendido) {
            estenderDropdown();
        } else {
            retrairDropdown();
        }
        
        actionListenerDropdown = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ev) {
                if (getDropdownEstendido()) {
                    retrairDropdown();
                } else {
                    estenderDropdown();
                }
            }
        };
        jHeaderLivro.addActionListenerDropdown(actionListenerDropdown);
        
        ActionListener listenerButtonAdicionar = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ev) {
                JMain.getInstancia().livros.add(livro);
            }
        };
        jHeaderLivro.addActionListenerAdicionarLivro(listenerButtonAdicionar);
    }
    
    @Override
    public final void atualizarConteudo() {
        jHeaderLivro.setConteudo(this.livro);
        jLivroEstendido.setConteudo(this.livro);
    }
    
    @Override
    public void estenderDropdown() {
        CardLayout layout = (CardLayout) jPanelDropdown.getLayout();
        layout.last(jPanelDropdown);
        jPanelDropdown.setPreferredSize(jLivroEstendido.getPreferredSize());
        jPanelDropdown.setMinimumSize(jLivroEstendido.getMinimumSize());
        jPanelDropdown.setMaximumSize(jLivroEstendido.getPreferredSize());
        dropdownEstendido = true;
    }
    
    @Override
    public void retrairDropdown() {
        CardLayout layout = (CardLayout) jPanelDropdown.getLayout();
        layout.first(jPanelDropdown);
        jPanelDropdown.setMinimumSize(new Dimension(jLivroEstendido.getWidth(), 1));
        jPanelDropdown.setPreferredSize(new Dimension(
            jLivroEstendido.getPreferredSize().width, 1));
        jPanelDropdown.setMaximumSize(new Dimension(
            jLivroEstendido.getMaximumSize().width, 1));
        dropdownEstendido = false;
    }
    
    // ========== setters ==========
    
    @Override
    public void setLivro(Livro livro) {
        this.livro = livro;
    }
    
    @Override
    public void setDropdownEstendido(boolean valor) {
        if (valor) {
            this.estenderDropdown();
        } else {
            this.retrairDropdown();
        }
    }
    
    // ========== getters ==========
    
    @Override
    public Livro getLivro() { return livro; }
    
    @Override
    public boolean getDropdownEstendido() { return dropdownEstendido; }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeaderLivro = new widget.support.livro.JHeaderLivro();
        jPanelDropdown = new javax.swing.JPanel();
        jPanelVazio = new javax.swing.JPanel();
        jLivroEstendido = new widget.support.livro.JLivroEstendido();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(528, 0));

        jPanelDropdown.setLayout(new java.awt.CardLayout());

        jPanelVazio.setPreferredSize(new java.awt.Dimension(600, 0));

        javax.swing.GroupLayout jPanelVazioLayout = new javax.swing.GroupLayout(jPanelVazio);
        jPanelVazio.setLayout(jPanelVazioLayout);
        jPanelVazioLayout.setHorizontalGroup(
            jPanelVazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanelVazioLayout.setVerticalGroup(
            jPanelVazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        jPanelDropdown.add(jPanelVazio, "dropdownRetraido");
        jPanelDropdown.add(jLivroEstendido, "dropdownEstendido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHeaderLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDropdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHeaderLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDropdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.support.livro.JHeaderLivro jHeaderLivro;
    private widget.support.livro.JLivroEstendido jLivroEstendido;
    private javax.swing.JPanel jPanelDropdown;
    private javax.swing.JPanel jPanelVazio;
    // End of variables declaration//GEN-END:variables
}
