package widget.dados;

import model.Exemplar;

public class JDadosExemplar extends javax.swing.JPanel {
    
    private Exemplar exemplar;
    
    /**
     * Creates new form JDadosExemplar
     */
    public JDadosExemplar() {
        initComponents();
    }
    
    public JDadosExemplar(Exemplar exemplar) {
        this(); // chama o construtor padrão
        if (exemplar != null) {
            jTextFieldID.setText(String.valueOf(exemplar.getIdExemplar()));
            jTextFieldDataObtencao.setText(exemplar.getDataObtencao());
        }
        this.exemplar = exemplar;
    }
    
    // ========= SETTERS ==========
    
    public void setExemplar(Exemplar exemplar) {
        if (exemplar != null) {
            jTextFieldID.setText(String.valueOf(exemplar.getIdExemplar()));
            jTextFieldDataObtencao.setText(exemplar.getDataObtencao());
        } else {
            jTextFieldID.setText("");
            jTextFieldDataObtencao.setText("");
        }
        this.exemplar = exemplar;
    }
    
    // ========= GETTERS ==========
    
    public Exemplar getExemplar() {
        return this.exemplar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelDataObtencao = new javax.swing.JLabel();
        jTextFieldDataObtencao = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelID.setText("ID");

        jTextFieldID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jLabelDataObtencao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelDataObtencao.setText("Data de Obtenção");

        jTextFieldDataObtencao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldDataObtencao.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDataObtencao, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jTextFieldDataObtencao)
                    .addComponent(jTextFieldID)
                    .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDataObtencao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDataObtencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDataObtencao;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JTextField jTextFieldDataObtencao;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
