package widget.dados;

import model.Emprestimo;
import model.Livro;
import model.Exemplar;
import model.Usuario;

// dao
import dao.LivroDAO;
import dao.ExemplarDAO;
import dao.UsuarioDAO;


public class JDadosEmprestimo extends javax.swing.JPanel {

    private Emprestimo emprestimo;
    
    /**
     * Creates new form JDadosEmprestimo
     */
    public JDadosEmprestimo() {
        initComponents();
    }
    
    public JDadosEmprestimo(Emprestimo emprestimo) {
        this(); // chama o construtor padrão
        setEmprestimo(emprestimo);
    }
    
    // ========== SETTERS ==========
    
    public final void setEmprestimo(Emprestimo emprestimo) {
        
        if (emprestimo != null) {
            
            jTextFieldDataEmprestimo.setText(emprestimo.getDataEmprestimo());
            jTextFieldDataDevolucao.setText(emprestimo.getDataDevolucao());
            
            try {
                ExemplarDAO daoExemplar = new ExemplarDAO();
                Exemplar exemplar = daoExemplar.procurarExemplar(emprestimo.getIdEmprestimoExemplar());
                
                LivroDAO daoLivro = new LivroDAO();
                Livro livro = daoLivro.procurarLivro(exemplar.getIdExemplarLivro());
                
                jTextFieldTitulo.setText(livro.getNomeLivro());
                jTextFieldISBN.setText(livro.getISBNLivro());
                jTextFieldValor.setText(String.valueOf(livro.getPrecoLivro()) + " R$");
                
            } catch(RuntimeException e) {
                jTextFieldTitulo.setText("ERRO");
                jTextFieldISBN.setText("ERRO");
                jTextFieldValor.setText("ERRO");
                throw e;
            }
            
            try {
                UsuarioDAO dao = new UsuarioDAO();
                Usuario usuario = dao.procurarUsuario(emprestimo.getIdEmprestimoUsuario());
                jTextFieldUsuarioEmissor.setText(usuario.getNomeUsuario());
                
            } catch (RuntimeException e) {
                jTextFieldUsuarioEmissor.setText("ERRO");
                throw e;
            }
            
        } else {
            jTextFieldDataEmprestimo.setText("");
            jTextFieldDataDevolucao.setText("");
            jTextFieldTitulo.setText("");
            jTextFieldISBN.setText("");
            jTextFieldValor.setText("");
            jTextFieldUsuarioEmissor.setText("");
        }
        
        this.emprestimo = emprestimo;
    }
    
    // ========== GETTERS ==========
    
    public Emprestimo getEmprestimo() {
        return emprestimo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelISBN = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabelUsuarioEmissor = new javax.swing.JLabel();
        jTextFieldUsuarioEmissor = new javax.swing.JTextField();
        jLabelDataEmprestimo = new javax.swing.JLabel();
        jLabelDataDevolucao = new javax.swing.JLabel();
        jTextFieldDataEmprestimo = new javax.swing.JTextField();
        jTextFieldDataDevolucao = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 290));
        setMinimumSize(new java.awt.Dimension(400, 290));

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelTitulo.setText("Titulo do Livro");

        jTextFieldTitulo.setEditable(false);
        jTextFieldTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldTitulo.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jLabelISBN.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelISBN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelISBN.setText("ISBN");

        jTextFieldISBN.setEditable(false);
        jTextFieldISBN.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldISBN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldISBN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldISBN.setText("111-11-11-11-11-111");
        jTextFieldISBN.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jLabelUsuarioEmissor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelUsuarioEmissor.setText("Usuário Emissor");

        jTextFieldUsuarioEmissor.setEditable(false);
        jTextFieldUsuarioEmissor.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuarioEmissor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldUsuarioEmissor.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jLabelDataEmprestimo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelDataEmprestimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDataEmprestimo.setText("Data de Emprestimo");

        jLabelDataDevolucao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelDataDevolucao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDataDevolucao.setText("Data de Devolução");

        jTextFieldDataEmprestimo.setEditable(false);
        jTextFieldDataEmprestimo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataEmprestimo.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jTextFieldDataDevolucao.setEditable(false);
        jTextFieldDataDevolucao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDataDevolucao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldDataDevolucao.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jTextFieldValor.setEditable(false);
        jTextFieldValor.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldValor.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jLabelValor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValor.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUsuarioEmissor)
                    .addComponent(jTextFieldTitulo)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUsuarioEmissor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelDataDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDataEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jTextFieldDataEmprestimo)
                            .addComponent(jTextFieldDataDevolucao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelISBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldISBN)
                            .addComponent(jLabelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDataEmprestimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelDataDevolucao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelUsuarioEmissor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsuarioEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDataDevolucao;
    private javax.swing.JLabel jLabelDataEmprestimo;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuarioEmissor;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JTextField jTextFieldDataDevolucao;
    private javax.swing.JTextField jTextFieldDataEmprestimo;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldUsuarioEmissor;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
